INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE) VALUES ('Prakash', 'Sah', 36);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE) VALUES ('Sandeep', 'Kumar', 36);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE) VALUES ('Deepak', 'Sah', 35);